name: Build Ergohaven

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:

jobs:

  build-ergohaven:
    name: Build Ergohaven keymaps
    runs-on: ubuntu-latest
    # fixme: delete sha256 when upstream works
    container: ghcr.io/qmk/qmk_cli:latest@sha256:cd048bb28902adbde8c950b65ede93d058b398b380c6d28556c5f104b35f8840

    steps:
    - name: (actions) Checkout Vial repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        submodules: recursive

    - name: Build
      id: build
      run: |
        git config --global --add safe.directory $(pwd)
        qmk compile -kb ergohaven/k03 -km xellum
        # qmk compile -kb ergohaven/k03 -km velvetified
        # qmk compile -kb ergohaven/k03 -km v1_v2
        # qmk compile -kb ergohaven/k03 -km miryoku
        # qmk compile -kb ergohaven/k03 -km wellum
        # qmk compile -kb ergohaven/k03 -km wellum_ruen

    - uses: actions/upload-artifact@v4
      name: Upload
      id: upload
      with:
        path: "*.uf2"
        name: ergohaven_fw
