name: Build Keychron

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:

jobs:

  build-keychron:
    name: Build Keychron keymaps
    runs-on: ubuntu-latest
    # fixme: delete sha256 when upstream works
    container: ghcr.io/qmk/qmk_cli:latest@sha256:cd048bb28902adbde8c950b65ede93d058b398b380c6d28556c5f104b35f8840

    steps:
    - name: (actions) Checkout Vial repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        submodules: recursive

    - name: Build
      id: build
      run: |
        # qmk compile -kb keychron/k7_pro/ansi/rgb -km vial
        echo "Debugging Environment"
        echo "Git Version:"
        git --version || echo "Git not available"
        echo "QMK_BIN:"
        which qmk || echo "qmk not found"
        echo "Building firmware..."
        make keychron/k7_pro/ansi/rgb:vial V=1

    - uses: actions/upload-artifact@v4
      name: Upload
      id: upload
      with:
        path: "*.uf2"
        name: keychron_fw
